/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Card_Game_Engine;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    class App{
        String getGreeting()
        {
            return "some not null message";
        }
    }


    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
